# Generated by Django 5.2.5 on 2025-08-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=100, verbose_name='Nombre del Organizador')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de Fin')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.meetingroom', verbose_name='Sala')),
            ],
        ),
    ]
